apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: schema-reg
  name: schema-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-reg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: schema-reg
    spec:
      containers:
        - image: confluentinc/cp-schema-registry:7.5.0
          name: cp-schema-registry
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'broker:29092'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: schema-reg
  name: schema-reg
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: schema-reg
  type: ClusterIP


