apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - image: grafana/tempo:2.2.2
          args: ["-config.file=/etc/tempo.yaml"]
          name: tempo
          ports:
            - containerPort: 3200
              name: tempo
            - containerPort: 9411
              name: zipkin
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-data
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
      name: tempo
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: zipkin
  selector:
    app: tempo
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    
    distributor:
      receivers:
        zipkin:
    
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/tempo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi